Feature/button #13
ossia/qml-remote pull request #30
Opened 2021-06-07 12:28 UTC by Toine-ddt

2021-06-10 11:53 UTC, jcelerier commented
so, what's the status with this ?
is all the "relevant code" contained inside the two following commits ? 

```
@Toine-ddt add Button but it's does't work 4c41e72
@Toine-ddt buttons work : remote 2 score cf4d45c 
```

2021-06-10 12:26 UTC, Toine-ddt commented
> so, what's the status with this ?
> is all the "relevant code" contained inside the two following commits ?
> 
> ```
> @Toine-ddt add Button but it's does't work 4c41e72
> @Toine-ddt buttons work : remote 2 score cf4d45c 
> ```

yes ! It is all the "revelant code" for buttons

2021-06-10 13:01 UTC, jcelerier commented
okay I removed the unneeded commits then ; there may still be some fixes to do (e.g. the button uuid)

2021-06-10 13:06 UTC, jcelerier commented
here's my bash history: 

```
11425  cd ossia/qml-remote/

# Update my repo
11428  git checkout feature/Button
11429  git pull
11430  git checkout main
11427  git pull

# Import the first commit on my local main
11432  git cherry-pick feature/button~1

# Fix a conflict:
11436  code src/ControlSurface/ScoreControlSurface.qml 
11439  git add src/ControlSurface/ScoreControlSurface.qml
11440  git cherry-pick --continue

# Import the second commit on top of that commit, this one had no conflicts
11441  git cherry-pick feature/button~0

# Push my "main" to the Github "feature/Button" branch
11445  git push origin --force HEAD:feature/Button

# Reset my "main" to Github's main
11446  git reset --hard origin/main

```

2021-06-10 13:07 UTC, jcelerier commented on src/ControlSurface/ScoreControlSurface.qml
> +                case "fb27e4cb-ea7f-41e2-ad92-2354498c1b6b":
here

2021-06-10 13:08 UTC, jcelerier requested changes
pls

2021-06-10 13:21 UTC, jcelerier commented
noo all the commits are back :(

2021-06-10 13:25 UTC, Toine-ddt commented
> noo all the commits are back :(

yes... I did not understand why ?
As I use github desktop, it is different from git bash, so I don't master everything yet. I am so sorry :(

2021-06-10 14:06 UTC, jcelerier commented
arf yes, I had a hunch that this is because of gh desktop. I'd recommend switching to the CLI it's much less opaque

2021-06-17 08:05 UTC, jcelerier commented
I made a new branch, feature/button-2

2021-06-17 08:06 UTC, closed without merging